"""add schema metadata

Revision ID: 72f9104d6d0f
Revises: e8010327393e
Create Date: 2026-05-12 11:07:01.205479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f9104d6d0f'
down_revision: Union[str, Sequence[str], None] = 'e8010327393e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('column_name', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_metadata_id'), 'schema_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_metadata_id'), table_name='schema_metadata')
    op.drop_table('schema_metadata')
    # ### end Alembic commands ###
